image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: notify
    visibility: public
  - port: 8181
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install Node modules'
    init: |
        nvm install
        nvm use
        npm ci
        npm test

  - name: 'Serenity Reports'
    command: >
      npx http-server -p 8080 target/site/serenity

  - name: 'Playwright Report'
    command: >
      npx http-server -p 8181 playwright-report      

  - name: 'Welcome'
    command: |
      echo "To view Serenity Reports, visit:"
      gp url 8080
      echo "To view Playwright Report, visit:"
      gp url 8181

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - ms-playwright.playwright

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true
